services:
  - docker

env:
  - NAME=jat001/dog-tunnel

install: true

before_script:
  - FILE=$(wget -nv --content-disposition http://dog-tunnel.tk/download/linux64 2>&1 | grep -oP '(?<=").+(?=")')
  - VER=$(echo "$FILE" | grep -oP '\d[\d.]+\d')

  - curl -f "https://index.docker.io/v1/repositories/$NAME/tags/$VER" && travis_terminate 0
  - tar -xzf "$FILE"

  - docker login -u=jat001 -p="$DOCKER_PASSWD"

script:
  - docker build -t "$NAME:$VER" --build-arg "VER=$VER" .
  - docker tag "$NAME:$VER" "$NAME:latest"

  - docker push "$NAME:$VER"
  - docker push "$NAME:latest"
